language: python

python:
  - 3.5

addons:
  apt:
    packages:
      - pyqt5-dev-tools

git:
  submodules: false

before_install:
  - >-
    openssl aes-256-cbc
    -K $encrypted_0b023fb27a48_key
    -iv $encrypted_0b023fb27a48_iv
    -in github_deploy_key.enc
    -out github_deploy_key
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
  - git submodule update --init --recursive

install:
  - pip install -r requirements.txt

script:
  - scripts/ci/deploy.sh

env:
  global:
    - OSGEO_USERNAME=3nids
    # Inject OSGEO_PASSWORD matching the OSGEO_USERNAME
    # Generate with the following command for proper special characters support
    #     travis encrypt OSGEO_PASSWORD=\''Your super secret password!'\'
    - secure: "JTcQtn4nvMevskR2A6ebIOnxNVpui/Rum6o4Gz6W4QiLM6WEK8QhLufB/v34j3l0kLrlXF1gbuEv/Jgq85FhOW+a5sAz3zr23yEph924oUW4b5EawFDkx3etFXaKtOLKLAbFo2eWA2lXS2c5vtbnmQ+aeTUDulw9OOZKv/HypvpZsWSa7MnSXrNX+b9pYl2Axpc1oyhvci7q0xapsZOk8O1m15JCR0Oh5KZPlUn8fSBA2ARn70e/SKjVaCtQuuFDL6Pe+0CB2bAkQDnBY9ajvd5DIBCDMwq+8UxpiA5bj9qV4zXo0MyUWb3sgiU54tzgGgsiDbGJ8/fcrHEcJhu/nhAeVGOtDKF4+WmbtASiuIJqGOE8Qy7WDXHntLck31E0zFV85ScW5dcGvCzBDT7RKTdFG07p9zQGTKX785FGEjBkopIEvPs60kORog6MKLMFvLTNsjrvQnie2Fn8NYQ+vKYunqgbbBkCEvX7OXGrk87NrX6YtxwJQ5J3bPdh7TxL83Jfe5O+Clq5if8M7YDKDnP+QP5t+eF+WNDHaIAFIr0jTcop2d9acOBKSabbC8eTAXayu8V3JywqDS4jJdnd1ifQs9/vO8Qi8qsw+pBJBoHJ2PGfwbSgIhyS5YZBKA31Rxw8RFJpvs6HIDLeQyzdnh6zLAP3SQGPWHY1al9JUhQ="
    # TRANSIFEX_API_TOKEN <- personal access token for github to deploy on "releases"
    # https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
    - secure: "BezRhSTdJUF3Lkh+PknVonzD3KpSw46gmghwEI2+rafzt1jdj5ur/8mJyIxRd2Sx7nOcUrTVaRIVfS/vTCj5BC1UhcwNEdBmqLA1cdPJ/FHzqDJlC8jjXKg3xwHMNH9AcNbf35TeODFg1CQdsBflsljhj93Ajfda2N3XqR/BUwV/FbpRRVdDmtSS+deY0VaujL+XPe9PpPLPMsap+JhR+a5Xz8Sxf2DWhqqCT74ROce/YPBxw8l+O5/jgb0ndg0hkzuGtNoQvD2Ma28TgBGaiEkgoXEg86G8/itftLxt4dve+DBB2XffPNDHML/Vmz2nDsPXMXqV9/JHcIpeFyLw54CGVOy+Zdlnw272VBbHzsj0oEnx7P5bBdgefqQVgXI+WsAKYmYYdm/mCpZL8FDw959wyBZviJ9rePxGyDmOXF+X3bK+LNIpw7DOoM8GwUV5xi5c9mGGKdNKMshfD3f3INZd6gKdR2yUwKKSOQveRzWqT8dZTOIsGfBFwOOX/gXLCD2XuDEDotnl/GpwEwte+vT29GIqokR6oykFtFT69FL2t1Af09GY10zaZIp0ZE1KNpk54ZVMadrWyYU+15Shqfs2CMq5sjEBGvtEZYJhvMKsu+0XyiGt9PK88So7K6ELUpDwdcFuz4o3By4l5W5EGe+JJS01WyHpDMYuVGhYbvA="
