language: python
python:
  - 3.5

before_install:
  - >-
    openssl aes-256-cbc
    -K $encrypted_0b023fb27a48_key
    -iv $encrypted_0b023fb27a48_iv
    -in github_deploy_key.enc
    -out github_deploy_key
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key

install:
  - pip install -r requirements.txt

script:
  - scripts/ci/deploy.sh

env:
  global:
    - OSGEO_USERNAME=3nids
    # Inject OSGEO_PASSWORD matching the OSGEO_USERNAME
    # Generate with the following command for proper special characters support
    #     travis encrypt OSGEO_PASSWORD=\''Your super secret password!'\'
    - secure: "JTcQtn4nvMevskR2A6ebIOnxNVpui/Rum6o4Gz6W4QiLM6WEK8QhLufB/v34j3l0kLrlXF1gbuEv/Jgq85FhOW+a5sAz3zr23yEph924oUW4b5EawFDkx3etFXaKtOLKLAbFo2eWA2lXS2c5vtbnmQ+aeTUDulw9OOZKv/HypvpZsWSa7MnSXrNX+b9pYl2Axpc1oyhvci7q0xapsZOk8O1m15JCR0Oh5KZPlUn8fSBA2ARn70e/SKjVaCtQuuFDL6Pe+0CB2bAkQDnBY9ajvd5DIBCDMwq+8UxpiA5bj9qV4zXo0MyUWb3sgiU54tzgGgsiDbGJ8/fcrHEcJhu/nhAeVGOtDKF4+WmbtASiuIJqGOE8Qy7WDXHntLck31E0zFV85ScW5dcGvCzBDT7RKTdFG07p9zQGTKX785FGEjBkopIEvPs60kORog6MKLMFvLTNsjrvQnie2Fn8NYQ+vKYunqgbbBkCEvX7OXGrk87NrX6YtxwJQ5J3bPdh7TxL83Jfe5O+Clq5if8M7YDKDnP+QP5t+eF+WNDHaIAFIr0jTcop2d9acOBKSabbC8eTAXayu8V3JywqDS4jJdnd1ifQs9/vO8Qi8qsw+pBJBoHJ2PGfwbSgIhyS5YZBKA31Rxw8RFJpvs6HIDLeQyzdnh6zLAP3SQGPWHY1al9JUhQ="
    # OAUTH_TOKEN <- personal access token for github to deploy on "releases"
    # https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
    # - secure: "L7r1CSoeYqKytcb65OU/ni1DZBO0b7LiSLpkMl3IDwFeggJsURb1+GVLCMzDVoWqE+EtqbjyUySjyufgPMiu2IH9S9Tw/PMPZjlR3udzq/c5SLUaPbewpNRF5dAbIX3huVJSnJRez8NvQWQxgs0t4o+WsbhGoP2AirOkKR5Gp8BlOHKaNjxzdulrB1XHuW/ih0rNhRRflQF5H7N1QT4rWcIhhHcnTK76kFKyruGpPHnQ4ZwLqXbu68M9dNTB7P2m6K+4ZDFOc6gjK7uStfNnprhs3WA++rIFdvEPVHDmgEhnSqCosRsqs18bIZR1cvPrJzzu66eX1qFv4ETMX9NZeeiH3xx2b1wjM0jxy1WCH103BkzylIGUoKD+3zQuDBHSIkev2/QUUeBQaYZNZtad1ggp2MBtzswwl8Qsjyz7NtwS1vDGNDcL+OIZCxn1p3UDwQP9t+zpXy+CFbxPn7W38QFxvat9ztlhAUi5Y5x7U9jKmumxJBzKrY/Wv1lsYdvc/2aK5Eo+/SZnn+tGv4rM9xDm7OuEiit5yMn1/s6w/qjQ1vaXgCE7tWCTwNnuLNL0FS+Hiq+QxFJa4hkHTjhjOp4r2SClOGCSQRssgTfbZtEWMSYgoM52CsY4QUQqz7c2CdpNMw814r81mJduU5B3kjhIOKRXFfjlYCOayo8TGWs="
