language: python

python:
  - 3.5

addons:
  apt:
    packages:
      - pyqt5-dev-tools

git:
  submodules: false

before_install:
  - >-
    openssl aes-256-cbc
    -K $encrypted_0b023fb27a48_key
    -iv $encrypted_0b023fb27a48_iv
    -in github_deploy_key.enc
    -out github_deploy_key
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
  - git submodule update --init --recursive

install:
  - pip install -r requirements.txt


jobs:
  include:
    - stage: deploy
      if: tag IS present
      script: plugin_ci/release/release.sh

    - stage: deploy
      if: branch = master
      script: plugin_ci/translate/update-translations.sh

env:
  global:
    # OSGEO credentials to release the plugin
    # Generate with the following command for proper special characters support
    # travis encrypt OSGEO_PASSWORD=\''Your super secret password!'\'
    - OSGEO_USERNAME=3nids
    - secure: "JTcQtn4nvMevskR2A6ebIOnxNVpui/Rum6o4Gz6W4QiLM6WEK8QhLufB/v34j3l0kLrlXF1gbuEv/Jgq85FhOW+a5sAz3zr23yEph924oUW4b5EawFDkx3etFXaKtOLKLAbFo2eWA2lXS2c5vtbnmQ+aeTUDulw9OOZKv/HypvpZsWSa7MnSXrNX+b9pYl2Axpc1oyhvci7q0xapsZOk8O1m15JCR0Oh5KZPlUn8fSBA2ARn70e/SKjVaCtQuuFDL6Pe+0CB2bAkQDnBY9ajvd5DIBCDMwq+8UxpiA5bj9qV4zXo0MyUWb3sgiU54tzgGgsiDbGJ8/fcrHEcJhu/nhAeVGOtDKF4+WmbtASiuIJqGOE8Qy7WDXHntLck31E0zFV85ScW5dcGvCzBDT7RKTdFG07p9zQGTKX785FGEjBkopIEvPs60kORog6MKLMFvLTNsjrvQnie2Fn8NYQ+vKYunqgbbBkCEvX7OXGrk87NrX6YtxwJQ5J3bPdh7TxL83Jfe5O+Clq5if8M7YDKDnP+QP5t+eF+WNDHaIAFIr0jTcop2d9acOBKSabbC8eTAXayu8V3JywqDS4jJdnd1ifQs9/vO8Qi8qsw+pBJBoHJ2PGfwbSgIhyS5YZBKA31Rxw8RFJpvs6HIDLeQyzdnh6zLAP3SQGPWHY1al9JUhQ="

    # TRANSIFEX_API_TOKEN, generated on Transifex website
    # travis encrypt TX_TOKEN="......"
    - secure: "BWqMLP66AkFIrPxFOH1MxiMjLctpo6ZZYCwY3/eTumZ1eP/+YC0uKQduIJUKIqLtXNVaH8YGs2VfpFUD0QguAOvsk0fnR90qWZPwS+cAecq0MwnvmmrQk3/P0xBqaDGtE6G4OF4eKyB10ZohHEHE3BIMhiZkZvZAJ8ngNGYU6dL1l1kTBPXj0wucE17RAn9MIzr7YbO16WmkPEl2nEhjh9+2S0bv1nqp1Z2we4kjCQk9TvrvxCrY+Ow037HKgxfTQd0GU2WLJPmzc9Jf1bikf4Cdx6KusyVhI2u2GeMElQZhkVacgy8iuzf9DQGRLOx/1XMcv+jlWexgcADE/oGsBAcejByUAIs4nc4Sj/rcE2I8G6UTAd/dKMktWgTmTO0KhICJLKksbGYhZ9nP9TTWeL99vJTH2HlQMUcn8UHhQLv0bo4SoA8gKGgKajRs8LKPZ//hhxicSlMhPKxO8k2nwUhZJsGFsTZQTZtvErXUPFZhmWwfoYWS4rfIw4Sl0WqlgsN3PHJanmuQUCulIkVOz3O7iE9gNtflCrp/amfwe2leQ+85mbVGmNAEWn4qcMpqK+cnsepRCRO5Qj0Wkfitw+pFk4oTptcyFwyqF3ItWOgrr866ULIU3D4Uk1M6+xMz2Q328SCbBrm4n/sQM3bwE53QQ4bQUWr0S8S8RrKdpdY="

    # GH_TOKEN for creating releases
    # https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line
    # authrize only "repo_deployment"
    # travis encrypt GH_TOKEN="......"
    secure: "CwhlKKyt/PGm8aRkJMHe66WoTftZxd390DglCqakuxi28FByMCu7kObm0fxVS1VvDUn2P1Cf1RcNRNAaC8098nLS5PYzro+VnWuDsXWDlGwKkyaxUhLE64lpbphIOIzGj3/78Vh3XzIEJktJx7r1PiWP5ce+i+wnWvOQLlqT5sCuVYoOcTGxvokIqx84tMT0wZAFputi2HS6aEaSLbKFKaOJnJ21nai6AvE8jUNWq7m2z+qfsw6aLOULStSkpRmA4FgC7s5gBkolWMRUq1+TFPYovTQ5Q+Vtlh545hwld2aVDlsaLXWkPceQ9TfTMic0YLeqhn/av937HtmzjB0IQpZ4GXza+KU2UGWQgCAxY/2xQeFH1VB/vzpfdJXU6QJTAl4iDcv9Cltgq2toXkbGZ44aSxN0R1M+s5K86cvecDY8+FfbAUuRTXIdqYpyjc1hCo49xFta2EdzvLMNzZmI2WRuQL0j4V49MJS7gmL8/CKAMEYavK4fUvyPcEU9FBTF9yZFPSDuSIOEbNjoAtjOxyu5Cu0VHQif69MjPBuUxnWLCE6DoFdX1Z7IV7SMzJsfEeKVR75Wq7D0IAKeNxAF+nl+Ypfumj051qAOPMfpyrps8DLkuRP5J10Z2050SZLK5A9ghe/b6TNW+PFanyD9nCIul85wGdQ9Ehy0iGHsM2U="
